const PREFIX_INCREMENT = 'toDoTaskData/';

export const ADD_TASK_LIST_REQUEST = `${PREFIX_INCREMENT}ADD/ADD_TASK_LIST_REQUEST`;
export const ADD_TASK_LIST_SUCCESS = `${PREFIX_INCREMENT}ADD/ADD_TASK_LIST_SUCCESS`;
export const ADD_TASK_LIST_FAILURE = `${PREFIX_INCREMENT}ADD/ADD_TASK_LIST_FAILURE`;

export const GET_TASK_LIST_REQUEST = `${PREFIX_INCREMENT}REQUEST/ADD_TASK_LIST_REQUEST`;
export const GET_TASK_LIST_SUCCESS = `${PREFIX_INCREMENT}SUCCESS/ADD_TASK_LIST_SUCCESS`;
export const GET_TASK_LIST_FAILURE = `${PREFIX_INCREMENT}FAILURE/ADD_TASK_LIST_FAILURE`;

export const DELETE_TASK_REQUEST = `${PREFIX_INCREMENT}REQUEST/DELETE_TASK_REQUEST`;
export const DELETE_TASK_SUCCESS = `${PREFIX_INCREMENT}SUCCESS/DELETE_TASK_SUCCESS`;
export const DELETE_TASK_FAILURE = `${PREFIX_INCREMENT}FAILURE/DELETE_TASK_FAILURE`;
